-- Agent's Exclusive Access Platform - Database Schema
-- Version: 1.0
-- Database: Cloudflare D1

-- Users table - stores authenticated real estate agents
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    stripe_customer_id TEXT,
    subscription_status TEXT DEFAULT 'inactive', -- active, inactive, trial, canceled
    subscription_tier TEXT DEFAULT 'basic', -- basic, pro, enterprise
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
);

-- Sessions table - for Lucia Auth
CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    expires_at INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Magic link tokens for authentication
CREATE TABLE IF NOT EXISTS magic_links (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    token TEXT UNIQUE NOT NULL,
    expires_at INTEGER NOT NULL,
    used BOOLEAN DEFAULT FALSE,
    created_at INTEGER NOT NULL
);

-- Content assets - PDFs, videos, reports generated by agents
CREATE TABLE IF NOT EXISTS content_assets (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    content_type TEXT NOT NULL, -- pdf, video, guide, report
    r2_key TEXT NOT NULL, -- key in R2 bucket
    file_size INTEGER,
    status TEXT DEFAULT 'active', -- active, archived, deleted
    view_count INTEGER DEFAULT 0,
    subscriber_count INTEGER DEFAULT 0,
    ai_prompt TEXT, -- the original prompt used to generate content
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Subscribers - people who access gated content
CREATE TABLE IF NOT EXISTS subscribers (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL, -- the agent who owns the content
    email TEXT NOT NULL,
    name TEXT,
    phone TEXT,
    source_asset_id TEXT, -- which asset they subscribed through
    created_at INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (source_asset_id) REFERENCES content_assets(id) ON DELETE SET NULL
);

-- Asset access tracking - which subscribers have access to which assets
CREATE TABLE IF NOT EXISTS asset_access (
    id TEXT PRIMARY KEY,
    subscriber_id TEXT NOT NULL,
    asset_id TEXT NOT NULL,
    accessed_at INTEGER NOT NULL,
    ip_address TEXT,
    user_agent TEXT,
    FOREIGN KEY (subscriber_id) REFERENCES subscribers(id) ON DELETE CASCADE,
    FOREIGN KEY (asset_id) REFERENCES content_assets(id) ON DELETE CASCADE,
    UNIQUE(subscriber_id, asset_id)
);

-- Analytics tracking
CREATE TABLE IF NOT EXISTS analytics_events (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    event_type TEXT NOT NULL, -- page_view, content_created, subscriber_added, etc.
    event_data TEXT, -- JSON blob
    created_at INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_magic_links_token ON magic_links(token);
CREATE INDEX IF NOT EXISTS idx_magic_links_email ON magic_links(email);
CREATE INDEX IF NOT EXISTS idx_content_assets_user_id ON content_assets(user_id);
CREATE INDEX IF NOT EXISTS idx_content_assets_status ON content_assets(status);
CREATE INDEX IF NOT EXISTS idx_subscribers_user_id ON subscribers(user_id);
CREATE INDEX IF NOT EXISTS idx_subscribers_email ON subscribers(email);
CREATE INDEX IF NOT EXISTS idx_asset_access_subscriber_id ON asset_access(subscriber_id);
CREATE INDEX IF NOT EXISTS idx_asset_access_asset_id ON asset_access(asset_id);
CREATE INDEX IF NOT EXISTS idx_analytics_user_id ON analytics_events(user_id);
CREATE INDEX IF NOT EXISTS idx_analytics_event_type ON analytics_events(event_type);
